from newt import main
f = main.addition(2, 2)
e = main.power(f, 10)
print(e, f)
result = main.op(main.increment, 5)
print(result)
result1 = main.op(main.decrement, 5)
print(result1)
f = main.nain()
r = f(10, 2)
print(r)
f = main.sain()
r = f(10, 2)
print(r)
f = main.dain()
r = f(10, 2)
print(r)
f = main.aain()
r = f(10, 2)
print(r)